
# Project information
site_name: QCentroid Quantum Platform Documentation
site_url: https://qcentroid.github.io/qcentroid-docs/
repo_url: https://github.com/qcentroid/qcentroid-docs/
site_description: This is the QCentroid Platform documentation site
site_author: QCentroid


nav:
- 'For users' :
    - 'Getting started': users/getting-started.md
    - 'How to create a problem': users/create-problem.md
    - 'How to create a solver': users/create-solver.md
    - 'How to update an existing solver': users/update-solver.md
    - 'How to launch a job (execute a problem)': users/launch-job-dashboard.md
    - 'How to see a job results': users/see-job-results.md
- 'Using the API and SDK' :
    - 'Getting started': api/getting-started.md
    - 'How to execute a problem': api/execute-problem-dashboard.md
- 'For administrators' :
    - 'Getting started': admins/getting-started.md
    - 'Deploy the infrastructure': deployment.md
    - 'Redeploy the platform': deployment.md
    - 'Restar the platform': deployment.md

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: custom
  logo: assets/images/qcentroid_docs_logo-1-260x30.png

extra_css:
  - qcentroid.css

markdown_extensions:
  - toc:
      permalink: 
      toc_depth: 3
  - codehilite
  - admonition
  - footnotes
  - def_list
  - abbr
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - smarty

plugins:
  - search


