
# Project information
site_name: QCentroid Quantum Platform Documentation
site_url: https://qcentroid.github.io/qcentroid-docs/
site_dir: 'site'
repo_url: https://github.com/qcentroid/qcentroid-docs/
site_description: This is the QCentroid Platform documentation site
site_author: QCentroid


nav:
- 'Using the Platform' :
    - 'Getting started': platform/getting-started.md
    - 'For creators' :
        - 'Getting started': platform/getting-started-creators.md
        - 'How to create a solver': platform/create-solver.md
        - 'How to create a problem': platform/create-problem.md
        - 'How to edit an existing problem': platform/edit-problem.md
        - 'How to update an existing solver': platform/edit-solver.md
    - 'For consumers' :
        - 'Getting started': platform/getting-started-consumers.md
        - 'Navigate through the problems': platform/browse-problems.md
        - 'How to launch a job (execute a problem)': platform/launch-job-dashboard.md
        - 'How to see a job results': platform/see-job-results.md
        - 'How to upload data files': platform/upload-data-file.md
- 'Using the API and SDK' :
    - 'Getting started': api/getting-started.md
    - 'Set up the SDK': api/setup-sdk.md
    - 'How to execute a problem': api/execute-problem-api.md


#- 'For administrators' :
#    - 'Getting started': admins/getting-started.md
#    - 'Platform architecture': admins/platform-architecture.md
#    - 'Troubleshooting': admins/troubleshooting.md
#    - 'Deploy the infrastructure': admins/deployment-aws-infrastructure.md
#    - 'Deploy the platform': admins/deployment-aws-platform.md
#    - 'Redeploy the platform': admins/deployment-aws-platform-redeployment.md
#    - 'Restart the platform': admins/restart-platform.md
#

theme:
  name: material
  features:
#    - navigation.footer
  palette:
    primary: custom
  logo: assets/images/qcentroid_docs_logo-1-260x30.png

extra_css:
  - qcentroid.css

markdown_extensions:
  - toc:
      permalink: '#'
      toc_depth: 3
  - codehilite
  - admonition
  - footnotes
  - def_list
  - abbr
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - smarty
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

plugins:
  - search


